//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLogin.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILoginWS")]
    public interface ILoginWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginWS/IsValid", ReplyAction="http://tempuri.org/ILoginWS/IsValidResponse")]
        bool IsValid(string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginWS/IsValid", ReplyAction="http://tempuri.org/ILoginWS/IsValidResponse")]
        System.Threading.Tasks.Task<bool> IsValidAsync(string username, string pwd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginWSChannel : UserLogin.ServiceReference1.ILoginWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginWSClient : System.ServiceModel.ClientBase<UserLogin.ServiceReference1.ILoginWS>, UserLogin.ServiceReference1.ILoginWS {
        
        public LoginWSClient() {
        }
        
        public LoginWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsValid(string username, string pwd) {
            return base.Channel.IsValid(username, pwd);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidAsync(string username, string pwd) {
            return base.Channel.IsValidAsync(username, pwd);
        }
    }
}
